name: netplayer_mobile
description: netPlayer mobile version.
publish_to: 'none'
version: 2.5.4

environment:
  sdk: '>=3.10.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  get: ^4.6.6
  http: ^1.2.2
  loading_animation_widget: ^1.2.1
  crypto: ^3.0.3
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
  audio_service: ^0.18.15
  scroll_to_index: ^3.0.1
  just_audio: ^0.9.37
  auto_size_text: ^3.0.0
  audio_session: ^0.1.21
  path_provider: ^2.1.4
  dropdown_button2: ^2.3.9
  connectivity_plus: ^6.0.5
  image: ^4.5.2
  package_info_plus: ^8.3.0
  clipboard: ^0.1.3
  forui: ^0.17.0
  permission_handler: ^12.0.0+1
  collection: ^1.19.1
  skeletons_forked: ^0.0.4
  dio: ^5.9.0
  path: ^1.9.1
  audio_metadata_reader: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: "PuHui"
      fonts:
        - asset: fonts/AlibabaPuHuiTi-3-Light.ttf
          weight: 300
        - asset: fonts/AlibabaPuHuiTi-3-Regular.ttf
          weight: 400
        - asset: fonts/AlibabaPuHuiTi-3-Bold.ttf
          weight: 700

flutter_native_splash:
  web: false
  color: "#ffffff"
  image: assets/icon.png